### ISSUE TITLE
Mobile Menu does not close independently if increase browser width

### ISSUE THREAD

**Issue by JoBurg007** [trujic1000/react-navbar#12]
I guess there is a little bug? If you use the mobile menu in a browser window with a small width of course, then don't close it and increase the windows width of the browser to the state where the DesktopNav becomes visible, the mobile menu does not disappear automatically.
Would it be possible to fix this? 
Kind regards

**Comment by trujic1000** [comment]
Hey, sorry for the delay, and thanks for noticing the bug. Even though I'm not completely sure if a regular user would be able to notice and replicate it, I fixed it anyway.
